export type Lang = 'en' | 'zh';

export const S = {
  en: {
    docLabel: "Documentation",
    menuLabel: "Menu",
    docsNav: "Docs",
    openBot: "Open @BubbleFlapBot",
    light: "Light",
    dark: "Dark",

    nav: {
      intro:      "Introduction",
      start:      "Getting Started",
      trading:    "Trading",
      wallet:     "Wallet",
      limit:      "Limit Orders",
      auto:       "Automation",
      flapsh:     "Flap.sh Discovery",
      research:   "Research",
      referral:   "Referral Rewards",
      tip:        "Tip System",
      lang:       "Languages",
      security:   "Security",
      commands:   "Commands",
      whitelabel: "White Label API",
    },

    hero: {
      subtitle: "A powerful Telegram trading bot for BNB Smart Chain — buy, sell, snipe, alert, and discover tokens, all from your phone.",
      version: "v1.0.0 · BNB Chain",
    },

    intro: {
      title: "Introduction",
      p1: "Bubble Flap Bot is a Telegram-native trading bot built for the BNB Smart Chain (BSC). It allows anyone to trade BEP-20 tokens directly inside Telegram — no browser, no wallet extension required.",
      p2: "Whether you want to buy a newly launched token, set a take-profit limit order, snipe a launch the moment it goes live, or get alerted when a token hits your target price — Bubble Flap Bot handles it all.",
      features: [
        ["🦋", "Instant Token Trading", "Buy and sell any BEP-20 token in seconds"],
        ["🎯", "Smart Sniper", "Auto-buy on a token's very first trade"],
        ["🔔", "Price Alerts", "Get notified when your target is hit"],
        ["📋", "Limit Orders", "Set buy/sell triggers that execute automatically"],
        ["🎓", "Graduated Tokens", "Trade tokens that bonded on Flap.sh launchpad"],
        ["🆕", "Newly Created", "Live feed of fresh Flap.sh token launches"],
        ["🔍", "Security Scanner", "AI-powered honeypot & risk analysis"],
        ["🌐", "Multi-Language", "8 languages supported"],
      ] as [string, string, string][],
    },

    start: {
      title: "Getting Started",
      intro: "Getting started takes under 30 seconds. No sign-up, no KYC.",
      steps: [
        ["Open the bot",            "Search @BubbleFlapBot on Telegram or click the link above."],
        ["Send /start",             "The bot automatically creates a non-custodial BNB Chain wallet for you."],
        ["Save your private key",   "Your private key is shown once on first start. Save it securely — treat it like a password."],
        ["Deposit BNB",             "Send BNB to your wallet address to fund trades. Tap Receive for your QR code."],
        ["Start trading",           "Paste any token contract address (CA) to open the trade panel and buy instantly."],
      ] as [string, string][],
      warnTitle: "⚠️ Important",
      warnText: "Your private key gives full access to your funds. Never share it with anyone, including support staff. Bubble Flap will never ask for your private key.",
    },

    trading: {
      title: "Trading",
      intro: "Bubble Flap Bot supports fast, flexible token swaps on BSC using PancakeSwap and additional routers.",
      panelTitle: "Trade Panel (Recommended)",
      panelDesc: "Paste any BEP-20 token contract address directly into the chat. The bot opens a full trade panel with:",
      panelFeatures: [
        "Quick buy buttons (0.02, 0.05, 0.1, 0.5 BNB)",
        "Custom BNB amount",
        "Sell % buttons (25%, 50%, 100%)",
        "Per-token slippage control",
        "Gas speed selector",
        "Auto Sell (TP/SL)",
        "Limit orders from panel",
      ],
      cmdTitle: "Command-line Trading",
      autoTitle: "Auto Sell — Take Profit & Stop Loss",
      autoDesc: "From the trade panel, configure automatic sell rules that trigger when your position reaches a set percentage gain or loss. Rules run 24/7 in the background.",
    },

    wallet: {
      title: "Wallet Management",
      intro: "Each Telegram account gets a dedicated non-custodial BNB Chain wallet. You can create and manage multiple wallets.",
      items: [
        ["Multiple wallets",        "Create, rename, and switch between wallets from the Account menu."],
        ["Default wallet",          "One wallet is always active for trades. Switch defaults any time."],
        ["Export private key",      "Access your private key at any time with /exportkey — keep it safe."],
        ["Receive (QR code)",       "Tap Receive to view your deposit address as a QR code for easy transfers."],
        ["Deposit notifications",   "The bot monitors your wallet and alerts you when BNB arrives."],
      ] as [string, string][],
    },

    limit: {
      title: "Limit Orders",
      intro: "Set buy or sell orders that execute automatically when a token reaches your target price — even while you sleep.",
      steps: [
        ["Open the Limit Orders panel", "Tap Limit Orders from the main menu or type /limit."],
        ["Select a token",              "Enter the token contract address."],
        ["Set your trigger price",      "Enter the BNB price at which you want to buy or sell."],
        ["Confirm the order",           "The bot monitors prices every 30 seconds and executes when the target is hit."],
      ] as [string, string][],
    },

    auto: {
      title: "Automation — Snipe & Alert",
      sniperTitle: "🎯 Sniper",
      sniperDesc: "The sniper watches for a token's very first on-chain trade and automatically buys when it detects it. Perfect for new launches.",
      sniperFmt: "Format: /snipe <CA> <BNB amount>",
      sniperOr: "Or tap the ",
      sniperBtn: "🎯 Snipe",
      sniperOr2: " button and paste the CA interactively.",
      alertTitle: "🔔 Price Alert",
      alertDesc: "Set a target multiplier on any token. The bot checks prices every 15 seconds and notifies you when the target is reached.",
      alertFmt: "Examples: 2x (double), 0.5x (50% drop), 3x (triple)",
      cancelTitle: "Cancel all automation",
      cancelDesc: "Cancels all active snipes and alerts.",
    },

    flapsh: {
      title: "Flap.sh Discovery",
      intro: "Bubble Flap Bot is natively connected to the Flap.sh launchpad — a BNB Smart Chain token launch platform. Every token launched on Flap.sh can be traded, sniped, or alerted directly through the bot.",
      gradTitle: "🎓 Graduated Tokens",
      gradDesc: "Tokens that completed their bonding curve and graduated to open trading on PancakeSwap.",
      gradItems: [
        "Fully bonded — liquidity locked and open",
        "Ideal for buyers who missed the launch",
        "Buy instantly with a single tap",
      ],
      newTitle: "🆕 Newly Created",
      newDesc: "A live feed of freshly launched tokens on Flap.sh — updated every 30 seconds. Get in early.",
      newItems: [
        "Real-time discovery of new launches",
        "Snipe or buy any token immediately",
        "First-mover advantage before hype",
      ],
      volumeTitle: "🚀 Supporting Flap.sh Volume",
      volumeDesc: "Every trade made through Bubble Flap Bot on a Flap.sh token contributes directly to that token's on-chain volume, helping grow a healthy ecosystem for all participants.",
      cmdsTitle: "Full Flap.sh Commands",
    },

    research: {
      title: "Research & AI Scanner",
      intro: "Bubble Flap Bot gives you real-time market intelligence and AI-powered token analysis — all in the same interface you trade with.",
      items: [
        ["🔍 AI Token Scan",  "/scan 0xCA",    "Full token report powered by Claude 3 Haiku + GoPlus + Dexscreener. Shows risk rating (🟢 LOW → 🔴 CRITICAL), honeypot status, buy/sell tax, LP lock %, top holders, volume, buy pressure, price trend, and quick-trade links. Displays the token's banner image if available."],
        ["🔥 Trending",       "/trending",     "Shows the most active tokens on BSC right now by volume."],
        ["🎓 Recent Bond",    "/recentbond",   "Tokens that recently graduated (bonded) on Flap.sh launchpad."],
        ["🆕 New Created",    "/newcreated",   "Live feed of newly deployed tokens — updates every 30 seconds."],
        ["📜 New Tokens",     "/new",          "Latest tokens from the Flap.sh launchpad."],
      ] as [string, string, string][],
    },

    referral: {
      title: "Referral Rewards",
      intro: "Invite friends to Bubble Flap Bot and earn BNB automatically every time they trade — no limits, no minimum invites required.",
      permanentTitle: "🔒 Your referral ID is permanent",
      permanentDesc: "Tied to your Telegram ID — never deleted, and stays the same even if you change your username. Once someone joins via your link they're linked to you permanently. Rewards are active for",
      permanentMonths: "6 months",
      permanentSuffix: "per invitee.",
      steps: [
        ["Get your referral link", "Tap 🎁 Referral in the main menu. Your personal link is shown at the top."],
        ["Share it",               "Send the link to anyone. When they open it and press Start, they're linked to you permanently."],
        ["Earn BNB",               "Every time your invitee makes a trade, BNB is credited to your referral balance automatically."],
        ["Claim anytime",          "Once you reach the minimum balance, tap Claim Reward and BNB is sent to your wallet."],
      ] as [string, string][],
      tierTitle: "🏅 Reward Tiers",
      tierBase: "Base:",
      tierBaseRate: "0.30% per trade (0–19 invitees)",
      tierVip: "⭐ VIP:",
      tierVipRate: "0.35% per trade (20+ invitees)",
      inviteeTitle: "🎟️ Invitee Benefit",
      inviteeDesc: "Users who join via a referral link get a",
      inviteeDiscount: "-0.1% fee discount",
      inviteeSuffix: "on every trade, automatically applied.",
      windowTitle: "6-month window",
      windowDesc: "Rewards active for 6 months per invitee",
      nocapTitle: "No cap",
      nocapDesc: "Refer as many people as you want",
      claimTitle: "Claim Rules",
      claimBadges: [
        "Minimum 0.01 BNB to claim",
        "Network gas deducted on claim",
        "Paid to your active BSC wallet",
        "Buys and sells both count",
      ],
    },

    tip: {
      title: "Tip System",
      intro: "Send BFLAP tokens directly to any Telegram user — inside the bot, in groups, or in channels. No wallet address needed.",
      methods: [
        ["By username", "/tip 10000 @aamon",            "Tip any user by their @username"],
        ["By reply",    "Reply to a message → /tip 10000", "Tip the person whose message you replied to — no @username needed, works even if they have no username"],
      ] as [string, string, string][],
      features: [
        ["BFLAP only",           "Tips are sent in the official BFLAP token (BEP-20 on BNB Chain). You need enough BNB to cover gas."],
        ["Auto-held tips",       "If the recipient hasn't started the bot yet, the tip is securely held and automatically transferred the moment they do /start."],
        ["💸 emoji scaling",     "Every $10 worth of BFLAP tipped adds one 💸 to the public notification — the bigger the tip, the more 💸 appear."],
        ["Group notifications",  "Success and failure messages appear in the group and auto-delete after 30 seconds to keep chats clean."],
        ["Rate limited",         "One tip per 30 seconds per user to prevent spam."],
      ] as [string, string][],
    },

    lang: {
      title: "Multi-Language Support",
      intro: "Bubble Flap Bot is available in 8 languages. Every user can set their own preferred language independently.",
      langs: [
        ["🇬🇧", "English",    "Default"],
        ["🇨🇳", "简体中文",   "Chinese"],
        ["🇮🇩", "Indonesia",  "Indonesian"],
        ["🇻🇳", "Tiếng Việt", "Vietnamese"],
        ["🇰🇷", "한국어",     "Korean"],
        ["🇯🇵", "日本語",     "Japanese"],
        ["🇳🇬", "Hausa",      "Hausa"],
        ["🇮🇳", "हिंदी",     "Hindi"],
      ] as [string, string, string][],
      switchText: "Tap",
      switchBtn: "🌐 Language",
      switchText2: "in the main menu to switch. Use",
      switchReset: "/clean",
      switchText3: "to reset back to English.",
    },

    security: {
      title: "Security & Safety",
      items: [
        ["Non-custodial wallets",  "Your wallet is generated from your Telegram ID using HD wallet derivation. You always hold your own keys."],
        ["Private key ownership",  "Export your private key at any time with /exportkey and import it into any external wallet (MetaMask, Trust Wallet, etc.)."],
        ["Token scanning",         "Before trading, use /scan to run a security analysis. The bot checks for honeypots, dangerous ownership patterns, and unusual tax structures."],
        ["Slippage control",       "Set per-token slippage to protect against sandwich attacks. Anti-MEV mode is available in Settings."],
        ["No third-party access",  "Only you can initiate trades from your bot session. No third party has access to your wallet or funds."],
      ] as [string, string][],
    },

    commands: {
      title: "Full Command Reference",
      groups: [
        ["Wallet", [
          ["/start",      "Open the dashboard. Creates your wallet on first use."],
          ["/wallet",     "View wallet address and BNB balance."],
          ["/exportkey",  "Export your private key (handle with care)."],
          ["/clean",      "Reset language preference back to English."],
        ]],
        ["Trading", [
          ["/buy <CA> <BNB>",      "Buy a token using BNB amount. Example: /buy 0x... 0.1"],
          ["/sell <CA> <percent>", "Sell a percentage of your token holdings. Example: /sell 0x... 50"],
        ]],
        ["Limit Orders & Automation", [
          ["/limit",          "View and manage your limit orders."],
          ["/snipe <CA> [BNB]", "Auto-buy a token on its first on-chain trade."],
          ["/alert <CA> <Nx>",  "Set a price alert at Nx multiplier. Example: /alert 0x... 2x"],
          ["/cancel",           "Cancel all active snipes and alerts."],
        ]],
        ["Research", [
          ["/scan <CA>",    "Security scan + AI analysis for any token."],
          ["/trending",     "Top trending tokens on BSC by volume."],
          ["/recentbond",   "Recently bonded tokens from Flap.sh."],
          ["/newcreated",   "Live feed of newly created tokens."],
          ["/new",          "Latest tokens from Flap.sh launchpad."],
        ]],
        ["Tipping", [
          ["/tip <amount> @username", "Tip BFLAP tokens to a user by username. Example: /tip 10000 @aamon"],
          ["/tip <amount> (reply)",   "Reply to any message and use /tip <amount> to tip that person directly — no username needed."],
        ]],
        ["Referral & Other", [
          ["/referral",  "Open your referral dashboard — link, rewards, and claims."],
          ["/history",   "View your full trade history."],
          ["/settings",  "Configure global slippage, gas, and other preferences."],
          ["/help",      "Show the in-bot help guide."],
        ]],
      ] as [string, [string, string][]][],
    },

    whitelabel: {
      title: "White Label API",
      intro: "Launch your own branded trading bot powered by BubbleFlap's infrastructure. Keep your branding — we handle the engine, security, and revenue share.",
      intro2: "No Replit required. Deploy on any VPS, Railway, Render, DigitalOcean, Hetzner, or any server with Node.js 18+ and MySQL/MariaDB.",
      customTitle: "What Operators Can Customize",
      customItems: [
        ["🤖", "Bot name & avatar"],
        ["📝", "Welcome message"],
        ["💰", "Tip token (any BEP-20)"],
        ["📖", "Docs page content"],
        ["🌐", "Custom domain"],
        ["🗣️", "Language selection"],
      ] as [string, string][],
      revenueTitle: "Operator Revenue Share",
      revenueItems: [
        ["Your share",     "0.1% goes to your wallet automatically"],
        ["Referral tree",  "You sit below BubbleFlap master, above all your users — your community earns you referral rewards too"],
      ] as [string, string][],
      featuresTitle: "Included Features",
      features: [
        ["Bot registry listing",    "Your bot is listed on the public BubbleFlap Bot Registry — free discovery and exposure for your community."],
        ["Volume dashboard",        "A private stats page showing your bot's total swap volume, active users, tips sent, and revenue earned — updated daily."],
        ["Custom referral tree",    "Your bot has its own referral system. Your users refer each other, and rewards flow up to you as the operator, then to BubbleFlap."],
        ["Full trading engine",     "Buy, sell, snipe, limit orders, alerts, auto-sell — all features included out of the box. Nothing to build."],
        ["8 languages",             "All 8 supported languages come pre-built. No translation work needed."],
        ["Multi-wallet support",    "Your users get full multi-wallet management, same as BubbleFlapBot."],
      ] as [string, string][],
      deployTitle: "Deployment Options",
      deployItems: [
        ["🖥️", "Any VPS",       "cPanel / WHM"],
        ["🚂", "Railway",       "Free tier available"],
        ["⚡", "Render",        "Auto-deploy from Git"],
        ["🌊", "DigitalOcean",  "Droplets / App Platform"],
        ["🇩🇪", "Hetzner",      "Affordable EU hosting"],
        ["☁️", "Any cloud",    "Node.js 18+ + MySQL"],
      ] as [string, string, string][],
      ctaTitle: "Interested in a White Label Bot?",
      ctaDesc: "Contact us on Telegram to apply for early operator access.",
    },

    footer: {
      powered: "Powered by @BubbleFlap · BNB Smart Chain",
      cta: "Start Trading with @BubbleFlapBot",
    },
  },

  zh: {
    docLabel: "文档",
    menuLabel: "菜单",
    docsNav: "文档",
    openBot: "打开 @BubbleFlapBot",
    light: "浅色",
    dark: "深色",

    nav: {
      intro:      "简介",
      start:      "快速开始",
      trading:    "交易",
      wallet:     "钱包",
      limit:      "限价订单",
      auto:       "自动化",
      flapsh:     "Flap.sh 发现",
      research:   "研究",
      referral:   "推荐奖励",
      tip:        "打赏系统",
      lang:       "语言",
      security:   "安全",
      commands:   "命令",
      whitelabel: "白标 API",
    },

    hero: {
      subtitle: "BNB 智能链上功能强大的 Telegram 交易机器人 — 在手机上即可买入、卖出、狙击、设置提醒、发现代币。",
      version: "v1.0.0 · BNB 链",
    },

    intro: {
      title: "简介",
      p1: "Bubble Flap Bot 是专为 BNB 智能链（BSC）构建的原生 Telegram 交易机器人。任何人都可以在 Telegram 内直接交易 BEP-20 代币，无需浏览器，无需钱包插件。",
      p2: "无论您想购买新发行的代币、设置止盈限价订单、在代币上线第一时间狙击，还是在代币达到目标价时收到通知 — Bubble Flap Bot 全部搞定。",
      features: [
        ["🦋", "即时代币交易",   "几秒内买卖任何 BEP-20 代币"],
        ["🎯", "智能狙击手",     "在代币第一笔交易时自动买入"],
        ["🔔", "价格提醒",       "目标价触达时立即通知您"],
        ["📋", "限价订单",       "设置自动执行的买卖触发条件"],
        ["🎓", "毕业代币",       "交易在 Flap.sh 完成绑定的代币"],
        ["🆕", "新上线代币",     "Flap.sh 新发代币实时动态"],
        ["🔍", "安全扫描仪",     "AI 驱动的貔貅检测与风险分析"],
        ["🌐", "多语言支持",     "支持 8 种语言"],
      ] as [string, string, string][],
    },

    start: {
      title: "快速开始",
      intro: "开始只需 30 秒。无需注册，无需 KYC。",
      steps: [
        ["打开机器人",    "在 Telegram 搜索 @BubbleFlapBot 或点击上方链接。"],
        ["发送 /start",  "机器人自动为您创建一个非托管 BNB 链钱包。"],
        ["保存私钥",     "私钥在首次启动时显示一次，请安全保存 — 将其视为密码保管。"],
        ["存入 BNB",     "向您的钱包地址转入 BNB 以备交易。点击「收款」查看二维码。"],
        ["开始交易",     "粘贴任意代币合约地址（CA）即可打开交易面板，立即买入。"],
      ] as [string, string][],
      warnTitle: "⚠️ 重要提示",
      warnText: "私钥可完全访问您的资产。切勿向任何人透露，包括客服人员。Bubble Flap 不会索要您的私钥。",
    },

    trading: {
      title: "交易",
      intro: "Bubble Flap Bot 通过 PancakeSwap 及多个路由器，支持快速灵活的 BSC 代币兑换。",
      panelTitle: "交易面板（推荐）",
      panelDesc: "将任意 BEP-20 代币合约地址直接粘贴到聊天框，机器人会打开完整的交易面板，包含：",
      panelFeatures: [
        "快速买入按钮（0.02、0.05、0.1、0.5 BNB）",
        "自定义 BNB 金额",
        "卖出比例按钮（25%、50%、100%）",
        "单代币滑点控制",
        "Gas 速度选择",
        "自动卖出（止盈/止损）",
        "面板内限价订单",
      ],
      cmdTitle: "命令行交易",
      autoTitle: "自动卖出 — 止盈 & 止损",
      autoDesc: "在交易面板中配置自动卖出规则，当仓位达到设定的盈利或亏损百分比时自动触发。规则 24/7 在后台运行。",
    },

    wallet: {
      title: "钱包管理",
      intro: "每个 Telegram 账号获得一个专属的非托管 BNB 链钱包，可创建和管理多个钱包。",
      items: [
        ["多钱包支持",    "在账户菜单中创建、重命名并切换钱包。"],
        ["默认钱包",      "始终有一个活跃钱包用于交易，随时可切换默认钱包。"],
        ["导出私钥",      "通过 /exportkey 随时访问您的私钥 — 请妥善保管。"],
        ["收款（二维码）", "点击「收款」以二维码形式查看存款地址，方便转账。"],
        ["存款通知",      "机器人监控您的钱包，BNB 到账时立即提醒您。"],
      ] as [string, string][],
    },

    limit: {
      title: "限价订单",
      intro: "设置在代币达到目标价时自动执行的买卖订单 — 即使在您睡觉时也能运行。",
      steps: [
        ["打开限价订单面板", "在主菜单点击「限价订单」或输入 /limit。"],
        ["选择代币",         "输入代币合约地址。"],
        ["设置触发价格",     "输入您希望买入或卖出时的 BNB 价格。"],
        ["确认订单",         "机器人每 30 秒监控一次价格，目标触达时自动执行。"],
      ] as [string, string][],
    },

    auto: {
      title: "自动化 — 狙击 & 提醒",
      sniperTitle: "🎯 狙击手",
      sniperDesc: "狙击手监听代币的第一笔链上交易，检测到时自动买入。非常适合新发代币。",
      sniperFmt: "格式：/snipe <合约地址> <BNB 金额>",
      sniperOr: "或点击 ",
      sniperBtn: "🎯 狙击",
      sniperOr2: " 按钮，交互式粘贴合约地址。",
      alertTitle: "🔔 价格提醒",
      alertDesc: "为任意代币设置目标倍数，机器人每 15 秒检查一次价格，达到目标时通知您。",
      alertFmt: "示例：2x（翻倍）、0.5x（跌50%）、3x（三倍）",
      cancelTitle: "取消所有自动化",
      cancelDesc: "取消所有活跃的狙击和提醒。",
    },

    flapsh: {
      title: "Flap.sh 发现",
      intro: "Bubble Flap Bot 与 Flap.sh 发射台原生连接 — Flap.sh 是 BNB 智能链上的代币发行平台。每个在 Flap.sh 发行的代币都可直接通过机器人进行交易、狙击或设置提醒。",
      gradTitle: "🎓 毕业代币",
      gradDesc: "已完成绑定曲线并毕业到 PancakeSwap 公开交易的代币。",
      gradItems: [
        "完全绑定 — 流动性已锁定并开放",
        "适合错过发行的买家",
        "一键即可立即买入",
      ],
      newTitle: "🆕 新创建代币",
      newDesc: "Flap.sh 上新鲜发行代币的实时动态 — 每 30 秒更新一次。抢先入场。",
      newItems: [
        "实时发现新发行代币",
        "立即狙击或买入任意代币",
        "在热度爆发前抢占先机",
      ],
      volumeTitle: "🚀 支持 Flap.sh 交易量",
      volumeDesc: "通过 Bubble Flap Bot 在 Flap.sh 代币上进行的每笔交易，都直接贡献到该代币的链上交易量，助力所有参与者共同建设健康生态。",
      cmdsTitle: "完整 Flap.sh 命令",
    },

    research: {
      title: "研究与 AI 扫描",
      intro: "Bubble Flap Bot 内置实时市场情报与 AI 代币分析，无需切换界面即可研究与交易。",
      items: [
        ["🔍 AI 代币扫描", "/scan 0xCA",    "由 Claude 3 Haiku + GoPlus + Dexscreener 驱动的完整代币报告。显示风险评级（🟢 低 → 🔴 危险）、貔貅检测、买卖税、流动性锁定比例、头部持仓、成交量、买入压力、价格趋势及快速交易链接，支持代币横幅图展示。"],
        ["🔥 热门榜单",   "/trending",     "显示当前 BSC 上按交易量排名最活跃的代币。"],
        ["🎓 近期毕业",   "/recentbond",   "最近在 Flap.sh 发射台完成绑定（毕业）的代币。"],
        ["🆕 新创建",     "/newcreated",   "新部署代币的实时动态 — 每 30 秒更新。"],
        ["📜 新代币",     "/new",          "来自 Flap.sh 发射台的最新代币。"],
      ] as [string, string, string][],
    },

    referral: {
      title: "推荐奖励",
      intro: "邀请好友加入 Bubble Flap Bot，每次他们交易时自动为您赚取 BNB — 无限制，无最低邀请人数要求。",
      permanentTitle: "🔒 您的推荐 ID 是永久的",
      permanentDesc: "与您的 Telegram ID 绑定 — 永不删除，即使更改用户名也不变。通过您的链接加入的用户将永久与您关联。每位受邀者的奖励有效期为",
      permanentMonths: "6 个月",
      permanentSuffix: "。",
      steps: [
        ["获取推荐链接", "在主菜单点击 🎁 推荐，您的专属链接显示在顶部。"],
        ["分享链接",     "将链接发给任何人，他们打开并点击「开始」后，即永久与您关联。"],
        ["赚取 BNB",    "每次受邀者交易，BNB 自动计入您的推荐余额。"],
        ["随时提取",     "余额达到最低要求后，点击「领取奖励」，BNB 发送到您的钱包。"],
      ] as [string, string][],
      tierTitle: "🏅 奖励等级",
      tierBase: "基础：",
      tierBaseRate: "每笔交易 0.30%（0–19 位受邀者）",
      tierVip: "⭐ VIP：",
      tierVipRate: "每笔交易 0.35%（20+ 位受邀者）",
      inviteeTitle: "🎟️ 受邀者福利",
      inviteeDesc: "通过推荐链接加入的用户在每笔交易上享受",
      inviteeDiscount: "-0.1% 手续费折扣",
      inviteeSuffix: "，自动应用。",
      windowTitle: "6 个月有效期",
      windowDesc: "每位受邀者的奖励有效期为 6 个月",
      nocapTitle: "无上限",
      nocapDesc: "可推荐任意数量的用户",
      claimTitle: "提取规则",
      claimBadges: [
        "最低提取 0.01 BNB",
        "提取时扣除网络 Gas 费",
        "支付到您的活跃 BSC 钱包",
        "买入和卖出均计入奖励",
      ],
    },

    tip: {
      title: "打赏系统",
      intro: "直接向任意 Telegram 用户发送 BFLAP 代币 — 在机器人中、群组或频道内均可。无需钱包地址。",
      methods: [
        ["按用户名",  "/tip 10000 @aamon",             "通过 @用户名 打赏任意用户"],
        ["通过回复",  "回复消息 → /tip 10000",          "回复某人的消息后使用 /tip <金额> 即可打赏 — 无需 @用户名，即使对方没有用户名也有效"],
      ] as [string, string, string][],
      features: [
        ["仅限 BFLAP",    "打赏以官方 BFLAP 代币（BNB 链 BEP-20）发送，需要足够的 BNB 支付 Gas。"],
        ["自动暂存打赏",  "如果收款方尚未启动机器人，打赏将安全暂存，待其 /start 后立即自动转账。"],
        ["💸 表情缩放",   "每价值 10 美元的 BFLAP 打赏会在公开通知中添加一个 💸 — 打赏越多，💸 越多。"],
        ["群组通知",      "成功和失败消息会出现在群组中，并在 30 秒后自动删除，保持聊天整洁。"],
        ["频率限制",      "每位用户每 30 秒最多一次打赏，防止滥用。"],
      ] as [string, string][],
    },

    lang: {
      title: "多语言支持",
      intro: "Bubble Flap Bot 支持 8 种语言，每位用户可独立设置自己偏好的语言。",
      langs: [
        ["🇬🇧", "English",    "默认"],
        ["🇨🇳", "简体中文",   "中文"],
        ["🇮🇩", "Indonesia",  "印尼语"],
        ["🇻🇳", "Tiếng Việt", "越南语"],
        ["🇰🇷", "한국어",     "韩语"],
        ["🇯🇵", "日本語",     "日语"],
        ["🇳🇬", "Hausa",      "豪萨语"],
        ["🇮🇳", "हिंदी",     "印地语"],
      ] as [string, string, string][],
      switchText: "在主菜单点击",
      switchBtn: "🌐 语言",
      switchText2: "切换语言。使用",
      switchReset: "/clean",
      switchText3: "重置为英语。",
    },

    security: {
      title: "安全与保障",
      items: [
        ["非托管钱包",    "您的钱包通过 Telegram ID 使用 HD 钱包推导生成，您始终持有自己的私钥。"],
        ["私钥所有权",    "通过 /exportkey 随时导出私钥，并导入任意外部钱包（MetaMask、Trust Wallet 等）。"],
        ["代币扫描",      "交易前使用 /scan 进行安全分析，机器人检查貔貅、危险所有权模式和异常税率结构。"],
        ["滑点控制",      "设置单代币滑点以防范三明治攻击。设置中提供防 MEV 模式。"],
        ["无第三方访问",  "只有您能从机器人会话发起交易，没有任何第三方可以访问您的钱包或资产。"],
      ] as [string, string][],
    },

    commands: {
      title: "完整命令参考",
      groups: [
        ["钱包", [
          ["/start",      "打开控制台，首次使用时创建钱包。"],
          ["/wallet",     "查看钱包地址和 BNB 余额。"],
          ["/exportkey",  "导出您的私钥（请谨慎操作）。"],
          ["/clean",      "将语言偏好重置为英语。"],
        ]],
        ["交易", [
          ["/buy <CA> <BNB>",      "使用 BNB 金额买入代币。示例：/buy 0x... 0.1"],
          ["/sell <CA> <percent>", "卖出持仓的指定百分比。示例：/sell 0x... 50"],
        ]],
        ["限价订单 & 自动化", [
          ["/limit",            "查看和管理限价订单。"],
          ["/snipe <CA> [BNB]", "在代币第一笔链上交易时自动买入。"],
          ["/alert <CA> <Nx>",  "设置 Nx 倍数价格提醒。示例：/alert 0x... 2x"],
          ["/cancel",           "取消所有活跃的狙击和提醒。"],
        ]],
        ["研究", [
          ["/scan <CA>",   "对任意代币进行安全扫描 + AI 分析。"],
          ["/trending",    "BSC 上按交易量排名的热门代币。"],
          ["/recentbond",  "Flap.sh 上近期完成绑定的代币。"],
          ["/newcreated",  "新创建代币的实时动态。"],
          ["/new",         "Flap.sh 发射台最新代币。"],
        ]],
        ["打赏", [
          ["/tip <金额> @用户名",  "按用户名打赏 BFLAP。示例：/tip 10000 @aamon"],
          ["/tip <金额>（回复）",  "回复任意消息后使用 /tip <金额> 直接打赏对方 — 无需用户名。"],
        ]],
        ["推荐 & 其他", [
          ["/referral",  "打开推荐控制台 — 链接、奖励和提取。"],
          ["/history",   "查看完整交易历史。"],
          ["/settings",  "配置全局滑点、Gas 及其他偏好设置。"],
          ["/help",      "显示机器人内置帮助指南。"],
        ]],
      ] as [string, [string, string][]][],
    },

    whitelabel: {
      title: "白标 API",
      intro: "使用 BubbleFlap 基础设施推出您自己的品牌交易机器人。保留您的品牌 — 我们负责引擎、安全和收益分成。",
      intro2: "无需 Replit。可部署在任意 VPS、Railway、Render、DigitalOcean、Hetzner 或任何支持 Node.js 18+ 和 MySQL/MariaDB 的服务器。",
      customTitle: "运营商可自定义内容",
      customItems: [
        ["🤖", "机器人名称 & 头像"],
        ["📝", "欢迎消息"],
        ["💰", "打赏代币（任意 BEP-20）"],
        ["📖", "文档页面内容"],
        ["🌐", "自定义域名"],
        ["🗣️", "语言选择"],
      ] as [string, string][],
      revenueTitle: "运营商收益分成",
      revenueItems: [
        ["您的分成",  "0.1% 自动发送到您的钱包"],
        ["推荐树",    "您处于 BubbleFlap 主节点之下，您的用户之上 — 您的社区也为您赚取推荐奖励"],
      ] as [string, string][],
      featuresTitle: "包含功能",
      features: [
        ["机器人注册上榜",  "您的机器人将被列入 BubbleFlap 公开机器人注册表 — 为您的社区提供免费曝光和流量。"],
        ["交易量控制台",    "私人统计页面，显示您机器人的总兑换量、活跃用户、发送打赏及收益 — 每日更新。"],
        ["自定义推荐树",    "您的机器人拥有自己的推荐系统，用户互相推荐，奖励流向您（运营商），再到 BubbleFlap。"],
        ["完整交易引擎",    "买入、卖出、狙击、限价订单、提醒、自动卖出 — 所有功能开箱即用，无需自行构建。"],
        ["8 种语言",        "所有 8 种支持语言均已内置，无需翻译工作。"],
        ["多钱包支持",      "您的用户获得完整的多钱包管理功能，与 BubbleFlapBot 相同。"],
      ] as [string, string][],
      deployTitle: "部署选项",
      deployItems: [
        ["🖥️", "任意 VPS",       "cPanel / WHM"],
        ["🚂", "Railway",        "免费套餐可用"],
        ["⚡", "Render",         "从 Git 自动部署"],
        ["🌊", "DigitalOcean",   "Droplets / 应用平台"],
        ["🇩🇪", "Hetzner",       "实惠的欧洲主机"],
        ["☁️", "任意云端",       "Node.js 18+ + MySQL"],
      ] as [string, string, string][],
      ctaTitle: "对白标机器人感兴趣？",
      ctaDesc: "在 Telegram 上联系我们申请早期运营商访问权限。",
    },

    footer: {
      powered: "由 @BubbleFlap 提供支持 · BNB 智能链",
      cta: "开始使用 @BubbleFlapBot 交易",
    },
  },
};
